FROM node:14-slim as builder

WORKDIR /usr/src/app


COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install

COPY . .

ARG BASE_URL
ENV REACT_APP_BASE_URL=${BASE_URL}


RUN npm run build

#copy into secondary cady stage

FROM caddy:2.4.3-alpine


ARG CADDYFILE

COPY ${CADDYFILE} /etc/caddy/Caddyfile


COPY --from=builder /usr/src/app/build/ /srv

EXPOSE 80

EXPOSE 443